language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
script:
  - cargo build --verbose --features="parallel,io,ser"
  - cargo test --verbose --features="parallel,io,ser"
