[package]
name = "image2"
version = "0.12.0"
authors = ["Zach Shipko <zachshipko@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpp = "0.5"
half = "1"
rayon = "1"
euclid = "0.22"
lazy_static = "1"

[build-dependencies]
cpp_build = "0.5"
