[package]
name = "image2"
version = "0.12.0"
authors = ["Zach Shipko <zachshipko@gmail.com>"]
license = "ISC"
keywords = ["image", "image-processing"]
repository = "https://github.com/zshipko/image2-rs"
documentation = "https://docs.rs/image2"
description = "A simple image processing library"
readme = "README.md"
edition = "2018"


[dependencies]
cpp = "0.5"
half = "1"
rayon = "1"
euclid = "0.22"
lazy_static = "1"
async-trait = "0.1"
futures = "0.3"
serde = {version = "1", optional = true, features = ["derive"]}

[build-dependencies]
cpp_build = "0.5"

[dev-dependencies]
smol = "*"

[features]
docs-rs = []

[package.metadata.docs.rs]
features = ["docs-rs"]
