[package]
name = "image2"
version = "0.1.0"
authors = ["Zach Shipko <zachshipko@gmail.com>"]

[dependencies]
num = "0.2"
rayon = "1"
euclid = "0.19"
rawloader = { version = "0.34", optional = true }
rscam = {version = "0.5", optional = true}

[features]
default = []
all = ["v4l", "raw"]
v4l = ["rscam"]
raw = ["rawloader"]
