[package]
name = "image2"
version = "0.5.0"
authors = ["Zach Shipko <zachshipko@gmail.com>"]
license = "ISC"
keywords = ["image", "image-processing"]
repository = "https://github.com/zshipko/image2-rs"
documentation = "https://docs.rs/image2"
description = "A simple image processing library"
readme = "README.md"
edition = "2018"

[dependencies]
num = "0.2"
rayon = "1"
euclid = "0.19"
lazy_static = "1"
rawloader = { version = "0.35", optional = true }
rscam = {version = "0.5", optional = true}
serde = {version = "1", optional = true}
serde_derive = {version = "1", optional = true}

[features]
default = []
all = ["v4l", "raw", "ser"]
v4l = ["rscam"]
raw = ["rawloader"]
ser = ["serde", "serde_derive"]
